name: HealthKitExporter

options:
  bundleIdPrefix: com.aidancornelius
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  createIntermediateGroups: true

packages:
  HealthKitUtility:
    path: .

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  HealthKitExporter:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: HealthKitExporter
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidancornelius.HealthKitExporter
        INFOPLIST_FILE: HealthKitExporter/Info.plist
        CODE_SIGN_ENTITLEMENTS: HealthKitExporter/HealthKitExporter.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"HealthKitExporter/Preview Content\""
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: HealthKitExporterWidgets
      - package: HealthKitUtility
        product: HealthKitTestData
    info:
      path: HealthKitExporter/Info.plist
      properties:
        UIBackgroundModes:
          - processing
          - fetch
          - background-processing
          - audio
          - location
        NSLocalNetworkUsageDescription: "This app uses the local network to stream health data between your device and simulator for development and testing purposes."
        NSBonjourServices:
          - "_healthkitstream._tcp"
        NSHealthShareUsageDescription: "Read your health data to export it for testing and development purposes"
        NSHealthUpdateUsageDescription: "Write synthetic test data to HealthKit in the simulator"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: HealthKitExporter/HealthKitExporter.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access:
          - health-records
        com.apple.developer.healthkit.background-delivery: true

  HealthKitExporterWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - HealthKitExporterWidgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aidancornelius.HealthKitExporter.HealthKitExporterWidgets
        INFOPLIST_FILE: HealthKitExporterWidgets/Info.plist
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        SKIP_INSTALL: YES
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: HealthKitExporterWidgets/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

schemes:
  HealthKitExporter:
    build:
      targets:
        HealthKitExporter: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
