name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: macos-14  # Apple Silicon runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

    - name: Show Xcode and Swift versions
      run: |
        xcodebuild -version
        swift --version

    - name: Build package
      run: |
        xcodebuild build \
          -scheme HealthKitUtility-Package \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1'

    - name: Run tests
      run: |
        xcodebuild test \
          -scheme HealthKitUtility-Package \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
          -enableCodeCoverage YES

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
